### ISSUE TITLE
Deprecated service used 

### ISSUE THREAD

**Issue by haaino** [golles/ha-knmi#103]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

Sine ha 2023.12 I’m getting this message 

Use weather.get_forecasts instead which supports multiple entities.

Please replace this service and adjust your automations and scripts and select submit to close this issue

### Integration version

1.6.1

### Home Assistant version

2023.12

### Python version

3.11

**Comment by golles** [comment]
Hi, this deprecated service is not due to this integration but due to a template sensor or automation you have. 
This change is poorly documented in the[Backward-incompatible changes](https://www.home-assistant.io/blog/2023/12/06/release-202312/#backward-incompatible-changes) and completely missing in the regular documentation [Service weather.get_forecast](https://www.home-assistant.io/integrations/weather/#service-weatherget_forecast).

See my issue https://github.com/home-assistant/core/issues/105160 on how you can update your template sensor
