### ISSUE TITLE
API issue (while 0 request are made)

### ISSUE THREAD

**Issue by timoverwoest** [golles/ha-knmi#115]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

Integration does not work anymore

### Integration version

1.7.1

### Home Assistant version

core-2024.1.5

### Python version

3.11.6

### Home Assistant log

```shell
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.knmi
Source: custom_components/knmi/config_flow.py:54
Integration: KNMI (documentation, issues)
First occurred: 11:45:20 (3 occurrences)
Last logged: 11:47:35

API key daily limit exceeded, try again tomorrow
```

### Diagnostics

```json
not possible anymore, removed integration and am not able to install anymore
```

### Additional information

API error on installation
<img width="625" alt="Scherm­afbeelding 2024-01-27 om 11 49 43" src="https://github.com/golles/ha-knmi/assets/23740848/e29ba3c8-f6ab-474b-b0ed-5941598c6b96">

**Comment by golles** [comment]
I see this as well, and for a couple of days, I also see a lot of timeouts.
I'm investigating this at the moment

**Comment by HiDiHo01** [comment]
it's working again

**Comment by golles** [comment]
I assume that the time-outs cause the update coordinator to retry, burning through the requests. When I was checking my account at https://weerlive.nl/api/toegang/account.php earlier today I had over 1200 requests, at the moment it is on 9 (doesn't seem to update live) and everything seems to be working fine. Also responses are back under 100ms.

Since a couple of days, I've locally increased the time-out to `120` here https://github.com/golles/ha-knmi/blob/main/custom_components/knmi/const.py#L7
I've also removed https://github.com/golles/ha-knmi/blob/main/custom_components/knmi/coordinator.py#L46 to test if this does not automatically retry

**Comment by HiDiHo01** [comment]
> I assume that the time-outs cause the update coordinator to retry, burning through the requests. When I was checking my account at https://weerlive.nl/api/toegang/account.php earlier today I had over 1200 requests, at the moment it is on 9 (doesn't seem to update live) and everything seems to be working fine. Also responses are back under 100ms.
> 
> Since a couple of days, I've locally increased the time-out to `120` here https://github.com/golles/ha-knmi/blob/main/custom_components/knmi/const.py#L7 I've also removed https://github.com/golles/ha-knmi/blob/main/custom_components/knmi/coordinator.py#L46 to test if this does not automatically retry

Was there a error? can you catch it?

**Comment by golles** [comment]
All API errors are caught, the annoying thing about time-out errors is that they cost an API call. However, you're not getting a response

**Comment by HiDiHo01** [comment]
Maybe you can count false calls or and adjust the refresh so it wont be out of api calls?

**Comment by golles** [comment]
Version `2.0.0` has been released with a diagnostic sensor for remaining API calls.
