### ISSUE TITLE
Integration not working due to API calls exceeded

### ISSUE THREAD

**Issue by TheFes** [golles/ha-knmi#155]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

`2024-06-20 08:40:16.761 ERROR (MainThread) [custom_components.knmi] Update failed! - API key daily limit exceeded, try again tomorrow`

It was also appearing yesterday. I was hoping it would work today.

### Integration version

2.2.0

### Home Assistant version

core 2024.6.0

### Python version

3.12

### Home Assistant log

```shell
`2024-06-20 08:40:16.761 ERROR (MainThread) [custom_components.knmi] Update failed! - API key daily limit exceeded, try again tomorrow`
```

**Comment by FreddyX078** [comment]
Same here, problem started yesterday.
Update interval is set at 300 seconds.

**Comment by koendiender** [comment]
Same thing here. I disabled the integration yesterday. When I enabled it again today I got the same error immediately

**Comment by koendiender** [comment]
It seems like an API issue. According to weerlive.nl I have done 1059 API requests today. Even though the integration was enabled for less than a minute. I am not using the API key anywhere else.

<img width="332" alt="image" src="https://github.com/golles/ha-knmi/assets/9695378/fbce85d2-a711-48aa-9172-ab0fff72a7bd">

**Comment by Sjoop1985** [comment]
Having the same issue. I looked at history of the "remaining API calls" sensor and saw some weird things:

- remaining API calls did not reset to 300 at midnight on June 19th, leading to the limit being reached around 1am (after the 12 calls margin that remain when polling every 5 minutes for 24 hours).
- The count appears also not to have reset today (20th), as I got an error message immediately upon retrying after midnight, like @koendiender 
- Some days ago, (14th or 15th, can't go back to check since I removed the integration and cannot setup again) the remaining count fluctuated during the day and went back to 300 in the middle of the day.

So it appears something is going wrong on the Weerlive side of things. I've sent an e-mail to admin@meteoserver.nl, since they issued my API key and are the ones managing the API. Will report back when they reply/fix.

**Comment by TheFes** [comment]
For me it started working again this morning.

**Comment by Earthweb-EWS** [comment]
I have the same problem since yesterday. I use my API key exclusive in Home Assistant and on the weerlive.nl website it says 0 request this day. I think it is a problem on their site.
At this moment the website displays this errormessage: SQLSTATE[HY000] [1040] Too many connections

**Comment by remkohat** [comment]
Same issue yesterday.
Set the update interval from 300 to 900.
Somewhere this morning it started working again. But only for a few hours.

While typing this it started working again all of a sudden.
Something reset on the meteoserver.nl side?

**Comment by FreddyX078** [comment]
It's working for a couple of hours!

**Comment by remkohat** [comment]
> It's working for a couple of hours!

Here it's still not.
Still unable to reinstall the integration.
`Unknown error fetching weatherdata, try again later`

Logging in to weerlive.nl it shows only 4 api requests today so that's not it.
And those 4 where tests with a webbrowser.

**Comment by remkohat** [comment]
Finally got it reinstalled and working again. As far as I can tell it's an IPv6 issue.
Changing IPv6 settings in HA so connection to api goes over IPv4 seems to do the trick for now.

**Comment by golles** [comment]
This issue was caused by a server migration that took place last week. The migration led to some temporary disruptions, but these have been resolved.

**Comment by remkohat** [comment]
No not all issues have been resolved.
I still can't connect through my HE IP64 tunnel.
It was working fine before all the mess.
Contacted MeteoServer's admin.
I hope (s)he can really solve all issues.

**Comment by golles** [comment]
I created a new issue for that, as it's something different than this issue, or at least it needs to be dealt with differently #157
