### ISSUE TITLE
API Response Missing

### ISSUE THREAD

**Issue by AbeltjeNL** [golles/ha-knmi#73]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

Integration is throwing some errors updating to the latest version (1.3.7) using core 2023.2.3.

### What version of this integration has the issue?

1.3.7

### What version of Home Assistant Core has the issue?

2023.2.4

### Home Assistant log

```
Deze fout is ontstaan door een aangepaste integratie.

: custom_components.knmi
Source: custom_components/knmi/__init__.py:117 
Integration: KNMI (documentation, issues) 
First occurred: 20:40:40 (13 occurrences) 
Last logged: 20:40:40

Value d2zon is missing in API response
Value plaats is missing in API response
Value samenv is missing in API response
Value verw is missing in API response
Value windkmh is missing in API response
```

### Additional information

Not using HACS, just the custom component.

**Comment by golles** [comment]
Hi. These are warnings, not errors. The reason you see these is informative to you, so that you know that some sensors won't update because of the missing values in the API. 

The integration is not crashing from this and as soon as the values are present again, it will recover and update the entities. 

If you don't want to see these warnings, you can configure your logger to ’error’, ’fatal’ or ’critical’ see https://www.home-assistant.io/integrations/logger/
In the readme you can also see how you can set the log level for this integration https://github.com/golles/ha-knmi here you should change ’debug’ to one of the values I mentioned above. 

If this happens very often, I would suggest you to contact the supplier and inform them of issues in their API.
